export const ActionTypes = {
    SET_PROFILE_ID: "SET_PROFILE_ID",
    SET_PROFILE_DATA: "SET_PROFILE_DATA",
    SET_PROFILE_FRIENDS: "SET_PROFILE_FRIENDS",
    SET_PROFILE_GAMES: "SET_PROFILE_GAMES",
    REMOVE_PROFILE: "REMOVE_PROFILE",
}